<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-26T14:54:55Z" name="Default suite" finished-at="2020-10-26T14:55:08Z" duration-ms="12864">
    <groups>
    </groups>
    <test started-at="2020-10-26T14:54:55Z" name="Default test" finished-at="2020-10-26T14:55:08Z" duration-ms="12864">
      <class name="lesson24.mixedAssert">
        <test-method is-config="true" signature="setUpDriver()[pri:0, instance:lesson24.mixedAssert@404bbcbd]" started-at="2020-10-26T14:54:55Z" name="setUpDriver" finished-at="2020-10-26T14:55:03Z" duration-ms="7853" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDriver -->
        <test-method signature="mixedAssertion()[pri:0, instance:lesson24.mixedAssert@404bbcbd]" started-at="2020-10-26T14:55:03Z" name="mixedAssertion" finished-at="2020-10-26T14:55:08Z" duration-ms="4293" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
First assert expected [true] but found [false],
Second assert expected [true] but found [false],
Third assert expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
First assert expected [true] but found [false],
Second assert expected [true] but found [false],
Third assert expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at lesson24.mixedAssert.mixedAssertion(mixedAssert.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mixedAssertion -->
        <test-method is-config="true" signature="close()[pri:0, instance:lesson24.mixedAssert@404bbcbd]" started-at="2020-10-26T14:55:08Z" name="close" finished-at="2020-10-26T14:55:08Z" duration-ms="644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- lesson24.mixedAssert -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
